# Generated by Django 2.1.4 on 2020-02-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('usertype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_bloodgroup', models.CharField(max_length=50)),
                ('baby_name', models.CharField(max_length=100)),
                ('baby_bloodgroup', models.CharField(max_length=50)),
                ('mother_age', models.CharField(max_length=50)),
                ('anganvadi', models.CharField(max_length=100)),
                ('baby_age', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('approve', models.CharField(max_length=50)),
                ('usertype', models.CharField(max_length=50)),
            ],
        ),
    ]
