# Generated by Django 2.1.4 on 2020-02-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_reg',
            name='email',
            field=models.CharField(default='user@email.com', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_reg',
            name='number',
            field=models.CharField(default='0000000000', max_length=50),
        ),
    ]
