# Generated by Django 2.1.4 on 2020-02-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0002_auto_20200217_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('licence_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('hospital', models.CharField(max_length=50)),
                ('usertype', models.CharField(max_length=50)),
            ],
        ),
    ]
