# Generated by Django 2.1.4 on 2020-02-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0003_tbl_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('worker_id_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=50)),
                ('usertype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='hospital',
            field=models.CharField(max_length=100),
        ),
    ]
