# Generated by Django 2.1.4 on 2020-02-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0004_auto_20200217_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=10000)),
                ('reply', models.CharField(max_length=50)),
                ('replymsg', models.CharField(max_length=10000)),
            ],
        ),
    ]
