# Generated by Django 2.1.4 on 2020-02-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0008_tbl_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_message',
        ),
    ]
