# Generated by Django 2.1.4 on 2020-02-18 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0011_tbl_mothermsg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_mothermsg',
        ),
    ]
