# Generated by Django 2.1.4 on 2020-02-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0012_delete_tbl_mothermsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_mothermsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_id', models.CharField(max_length=100)),
                ('re', models.CharField(max_length=50)),
                ('re_id', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=10000)),
            ],
        ),
    ]
